"""add views and set default to 0.

Revision ID: 06c9955908d2
Revises: 03ebadc97f36
Create Date: 2021-07-30 00:08:57.622901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c9955908d2'
down_revision = '03ebadc97f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'views')
    # ### end Alembic commands ###
