"""set default value of views to 0.

Revision ID: 51a991bc8b61
Revises: 2c25f2922f4f
Create Date: 2021-07-29 23:59:07.045895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a991bc8b61'
down_revision = '2c25f2922f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('view_times', sa.Integer(), nullable=True))
    op.drop_column('question', 'views')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('question', 'view_times')
    # ### end Alembic commands ###
