"""delete unique username true.

Revision ID: 901d8a76f72c
Revises: 00f66e49b32e
Create Date: 2021-08-09 22:45:49.669567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901d8a76f72c'
down_revision = '00f66e49b32e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answer_username_key', 'answer', type_='unique')
    op.drop_constraint('question_username_key', 'question', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('question_username_key', 'question', ['username'])
    op.create_unique_constraint('answer_username_key', 'answer', ['username'])
    # ### end Alembic commands ###
